services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecureyeah
      POSTGRES_DB: openclassroom
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  pgdata:
